# Copyright © 2022 Brandon Li. All rights reserved.

# ========================================================= #
#  RustFmt configuration for Solis.
#  See https://rust-lang.github.io/rustfmt
# ========================================================= #

max_width=120
single_line_if_else_max_width=100
struct_lit_width=70
use_field_init_shorthand=true
struct_variant_width=60